resource_group_name = "__AKS_RESOURCE_GROUP__"
cluster_name        = "__AKS_NAME__"
acr_name            = "__ACR_NAME__"
sql_name            = "__SQL_INSTANCE_NAME__"
db_admin_login      = "__DB_ADMIN_LOGIN__"
db_admin_password   = "__DB_ADMIN_PASSWORD__"
storage_name        = "__STORAGE_NAME__"
kubernetes_version  = "1.22.6"
